import { BarChart3,Download,FileText,Handshake,IndianRupee,Target } from 'lucide-react'; import { BarChart,Bar,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis } from 'recharts';
import { KpiCard } from '../../../../components/data-display/KpiCard';
import { Button } from '../../../../components/ui/Button';
import { Card, CardHeader } from '../../../../components/ui/Card';
import { useRequirements, useRfqs, usePurchaseOrders } from '../../../../services/buyer/hooks';
import { ScreenShell } from '../shared/ScreenShell';

const funnel=[{stage:'Matches',value:166},{stage:'Shortlisted',value:54},{stage:'Meetings',value:33},{stage:'RFQs',value:18},{stage:'POs',value:3}];
export default function BusinessImpactPage(){const req=useRequirements();const rfq=useRfqs();const po=usePurchaseOrders();const value=(po.data??[]).reduce((a,b)=>a+b.value.amount,0);return <ScreenShell screen={30} title="Conversion & Business Impact" subtitle="Track conversion and business impact from the event."><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="Total Opportunities" value={28} icon={Target}/><KpiCard label="RFQs Issued" value={rfq.data?.length??0} icon={FileText}/><KpiCard label="POs Placed" value={po.data?.length??0} icon={Handshake}/><KpiCard label="Business Value" value={new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',notation:'compact'}).format(value)} icon={IndianRupee}/></div><div className="mt-4 grid gap-4 lg:grid-cols-[1fr_.8fr]"><Card><CardHeader title="Conversion Funnel" subtitle="Distinct opportunity-stage counts; revised documents must not be double-counted."/><div className="h-72 p-4"><ResponsiveContainer width="100%" height="100%"><BarChart data={funnel} layout="vertical" margin={{left:20}}><CartesianGrid strokeDasharray="3 3"/><XAxis type="number"/><YAxis dataKey="stage" type="category" width={75}/><Tooltip/><Bar dataKey="value" fill="#003f9e" radius={[0,6,6,0]}/></BarChart></ResponsiveContainer></div></Card><Card><CardHeader title="Top Converted Suppliers"/><div className="space-y-3 p-5">{[['Precision Mach Tech Pvt. Ltd.','₹1.10 Cr'],['Omega Precision','₹0.85 Cr'],['Shree Components','₹0.43 Cr']].map(([s,v],i)=><div key={s} className="flex items-center justify-between rounded-xl bg-slate-50 p-3"><div className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-brand-100 text-xs font-extrabold text-brand-700">{i+1}</span><b className="text-xs">{s}</b></div><span className="text-xs font-extrabold text-emerald-600">{v}</span></div>)}</div></Card></div><div className="mt-4 flex justify-center"><Button variant="secondary"><Download className="h-4 w-4"/>Download Impact Report</Button></div></ScreenShell>;}
