import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query'; import { sellerRepository } from './sellerRepository'; import { sellerKeys } from './queryKeys';
export const useSellerSession=()=>useQuery({queryKey:sellerKeys.session,queryFn:sellerRepository.getSession,staleTime:300000});
export const useSellerDashboard=()=>useQuery({queryKey:sellerKeys.dashboard,queryFn:sellerRepository.getDashboard});
export const useSellerCapabilities=()=>useQuery({queryKey:sellerKeys.capabilities,queryFn:sellerRepository.listCapabilities});
export const useSellerCapability=(id:string)=>useQuery({queryKey:sellerKeys.capability(id),queryFn:()=>sellerRepository.getCapability(id),enabled:Boolean(id)});
export const useSellerOpportunities=()=>useQuery({queryKey:sellerKeys.opportunities,queryFn:sellerRepository.listOpportunities});
export const useSellerMeetings=()=>useQuery({queryKey:sellerKeys.meetings,queryFn:sellerRepository.listMeetings});
export const useSellerMeeting=(id:string)=>useQuery({queryKey:sellerKeys.meeting(id),queryFn:()=>sellerRepository.getMeeting(id),enabled:Boolean(id)});
export const useSellerMeetingOutcomes=()=>useQuery({queryKey:sellerKeys.meetingOutcomes,queryFn:sellerRepository.listMeetingOutcomes});
export function useSellerTransitionMeeting(){const qc=useQueryClient();return useMutation({mutationFn:({id,status,notes}:{id:string;status:string;notes?:string})=>sellerRepository.transitionMeeting(id,status,notes),onSuccess:x=>{qc.setQueryData(sellerKeys.meeting(x.id),x);qc.invalidateQueries({queryKey:sellerKeys.meetings});}});}
export function useSellerMeetingOutcome(){const qc=useQueryClient();return useMutation({mutationFn:({id,...payload}:{id:string;outcome:string;notes:string;actionItems?:{title:string;ownerUserId?:string;dueDate?:string}[]})=>sellerRepository.meetingOutcome(id,payload),onSuccess:x=>{qc.setQueryData(sellerKeys.meeting(x.meeting.id),x.meeting);qc.invalidateQueries({queryKey:sellerKeys.meetings});}});}
export const useSellerRfqs=()=>useQuery({queryKey:sellerKeys.rfqs,queryFn:sellerRepository.listRfqs});
export const useSellerAwards=()=>useQuery({queryKey:sellerKeys.awards,queryFn:sellerRepository.listAwards});
export const useSellerEngagements=()=>useQuery({queryKey:sellerKeys.engagements,queryFn:sellerRepository.listEngagements});
export const useSellerEngagementMessages=(engagementId:string)=>useQuery({queryKey:sellerKeys.engagementMessages(engagementId),queryFn:()=>sellerRepository.listEngagementMessages(engagementId),enabled:Boolean(engagementId)});
export function useSendSellerEngagementMessage(){const qc=useQueryClient();return useMutation({mutationFn:({engagementId,...payload}:{engagementId:string;senderOrganizationId:string;message:string})=>sellerRepository.sendEngagementMessage(engagementId,payload),onSuccess:(_,vars)=>qc.invalidateQueries({queryKey:sellerKeys.engagementMessages(vars.engagementId)})});}
export function useCreateCapability(){const qc=useQueryClient();return useMutation({mutationFn:sellerRepository.createCapability,onSuccess:()=>qc.invalidateQueries({queryKey:sellerKeys.capabilities})});}
export function useUpdateCapability(){const qc=useQueryClient();return useMutation({mutationFn:({id,payload,version}:{id:string;payload:unknown;version?:number})=>sellerRepository.updateCapability(id,payload,version),onSuccess:x=>{qc.setQueryData(sellerKeys.capability(x.id),x);qc.invalidateQueries({queryKey:sellerKeys.capabilities});}});}
export function useSaveDraftCapability(){const qc=useQueryClient();return useMutation({mutationFn:({id,payload,version}:{id:string;payload:unknown;version?:number})=>sellerRepository.saveDraft(id,payload,version),onSuccess:x=>{qc.setQueryData(sellerKeys.capability(x.id),x);qc.invalidateQueries({queryKey:sellerKeys.capabilities});}});}
export function useCapabilityStep(kind:'classification'|'technical'|'commercial'){const qc=useQueryClient();return useMutation({mutationFn:({id,payload,version}:{id:string;payload:unknown;version:number})=>kind==='classification'?sellerRepository.saveClassification(id,payload,version):kind==='technical'?sellerRepository.saveTechnical(id,payload,version):sellerRepository.saveCommercial(id,payload,version),onSuccess:x=>{qc.setQueryData(sellerKeys.capability(x.id),x);qc.invalidateQueries({queryKey:sellerKeys.capabilities});}});}
export function usePublishCapability(){const qc=useQueryClient();return useMutation({mutationFn:({id,version}:{id:string;version:number})=>sellerRepository.publish(id,version),onSuccess:x=>{qc.setQueryData(sellerKeys.capability(x.id),x);qc.invalidateQueries({queryKey:sellerKeys.capabilities});}});}
export function useSubmitQuotation(){const qc=useQueryClient();return useMutation({mutationFn:({rfqId,...payload}:{rfqId:string;sellerOrganizationId:string;currency:string;lines:{description:string;quantity:number;uomCode:string;unitPrice:number}[]})=>sellerRepository.submitQuotation(rfqId,payload),onSuccess:()=>qc.invalidateQueries({queryKey:sellerKeys.rfqs})});}
export const useSellerReports=()=>useQuery({queryKey:sellerKeys.reports,queryFn:sellerRepository.listReports});