CREATE SCHEMA IF NOT EXISTS stall_booking;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Common enum-like checks use VARCHAR columns for EF compatibility and simple migrations.
CREATE TABLE stall_booking.tenants (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code varchar(40) NOT NULL UNIQUE,
  name varchar(150) NOT NULL,
  legal_name varchar(180) NOT NULL,
  gstin varchar(15),
  pan varchar(10),
  address varchar(500) NOT NULL,
  city varchar(100) NOT NULL,
  state varchar(100) NOT NULL,
  country varchar(100) NOT NULL DEFAULT 'India',
  pincode varchar(12) NOT NULL,
  email varchar(150) NOT NULL,
  phone varchar(30) NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  deleted_by uuid,
  is_deleted boolean NOT NULL DEFAULT false,
  correlation_id varchar(100),
  CONSTRAINT ck_tenants_gstin CHECK (gstin IS NULL OR gstin ~ '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$'),
  CONSTRAINT ck_tenants_pan CHECK (pan IS NULL OR pan ~ '^[A-Z]{5}[0-9]{4}[A-Z]$')
);

CREATE TABLE stall_booking.events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES stall_booking.tenants(id),
  event_code varchar(50) NOT NULL,
  event_name varchar(200) NOT NULL,
  venue_name varchar(200) NOT NULL,
  venue_address varchar(500),
  city varchar(100),
  district varchar(100),
  state varchar(100),
  country varchar(100) NOT NULL DEFAULT 'India',
  start_date date NOT NULL,
  end_date date NOT NULL,
  booking_open_date date NOT NULL,
  booking_close_date date NOT NULL,
  stall_block_validity_days int NOT NULL DEFAULT 3,
  default_gst_percentage numeric(5,2) NOT NULL DEFAULT 18.00,
  status varchar(40) NOT NULL DEFAULT 'Open',
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  deleted_by uuid,
  is_deleted boolean NOT NULL DEFAULT false,
  correlation_id varchar(100),
  UNIQUE (tenant_id, event_code),
  CONSTRAINT ck_events_dates CHECK (end_date >= start_date AND booking_close_date >= booking_open_date),
  CONSTRAINT ck_events_status CHECK (status IN ('Draft','Open','Closed','Completed','Cancelled'))
);

CREATE TABLE stall_booking.stall_sizes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES stall_booking.tenants(id),
  event_id uuid NOT NULL REFERENCES stall_booking.events(id),
  code varchar(20) NOT NULL,
  display_name varchar(80) NOT NULL,
  width_m numeric(8,2) NOT NULL,
  depth_m numeric(8,2) NOT NULL,
  area_sq_m numeric(8,2) NOT NULL,
  base_amount numeric(14,2) NOT NULL,
  gst_percentage numeric(5,2) NOT NULL,
  total_amount numeric(14,2) NOT NULL,
  currency char(3) NOT NULL DEFAULT 'INR',
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  deleted_by uuid,
  is_deleted boolean NOT NULL DEFAULT false,
  correlation_id varchar(100),
  UNIQUE (event_id, code),
  CONSTRAINT ck_stall_sizes_positive CHECK (width_m > 0 AND depth_m > 0 AND area_sq_m > 0 AND base_amount >= 0),
  CONSTRAINT ck_stall_sizes_total CHECK (total_amount = round(base_amount + (base_amount * gst_percentage / 100), 2))
);

CREATE TABLE stall_booking.stalls (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES stall_booking.tenants(id),
  event_id uuid NOT NULL REFERENCES stall_booking.events(id),
  stall_size_id uuid NOT NULL REFERENCES stall_booking.stall_sizes(id),
  stall_number varchar(40) NOT NULL,
  hall_name varchar(80),
  zone_name varchar(80),
  row_label varchar(40),
  floor_label varchar(40),
  layout_x int,
  layout_y int,
  current_status varchar(40) NOT NULL DEFAULT 'Available',
  current_booking_id uuid,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  deleted_by uuid,
  is_deleted boolean NOT NULL DEFAULT false,
  correlation_id varchar(100),
  UNIQUE (event_id, stall_number),
  CONSTRAINT ck_stalls_status CHECK (current_status IN ('Available','Blocked','Frozen','Released','Cancelled','Disabled'))
);

CREATE TABLE stall_booking.exhibitors (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES stall_booking.tenants(id),
  legal_name varchar(150) NOT NULL,
  trade_name varchar(150),
  registered_address varchar(500) NOT NULL,
  city varchar(100) NOT NULL,
  district varchar(100) NOT NULL,
  state varchar(100) NOT NULL,
  pincode varchar(12) NOT NULL,
  country varchar(100) NOT NULL DEFAULT 'India',
  contact_person_name varchar(100) NOT NULL,
  contact_person_designation varchar(100) NOT NULL,
  mobile varchar(30) NOT NULL,
  alternate_mobile varchar(30),
  email varchar(150) NOT NULL,
  alternate_email varchar(150),
  website varchar(200),
  industry_scale varchar(40) NOT NULL,
  business_type varchar(60) NOT NULL,
  company_constitution varchar(60) NOT NULL,
  industry_category varchar(120) NOT NULL,
  product_service_description varchar(1000) NOT NULL,
  product_keywords varchar(250) NOT NULL,
  udyam_number varchar(30) NOT NULL,
  gstin varchar(15) NOT NULL,
  pan varchar(10) NOT NULL,
  lub_member boolean NOT NULL,
  lub_state varchar(100) NOT NULL,
  lub_chapter varchar(100) NOT NULL,
  lub_membership_number varchar(80),
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  deleted_by uuid,
  is_deleted boolean NOT NULL DEFAULT false,
  correlation_id varchar(100),
  CONSTRAINT ck_exhibitors_mobile CHECK (mobile ~ '^(\+91[-\s]?)?[6-9][0-9]{9}$'),
  CONSTRAINT ck_exhibitors_pan CHECK (pan ~ '^[A-Z]{5}[0-9]{4}[A-Z]$'),
  CONSTRAINT ck_exhibitors_gstin CHECK (gstin ~ '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$'),
  CONSTRAINT ck_exhibitors_lub_member CHECK (lub_member = false OR lub_membership_number IS NOT NULL)
);

CREATE UNIQUE INDEX ux_exhibitors_tenant_gstin ON stall_booking.exhibitors(tenant_id, gstin) WHERE is_deleted = false;
CREATE UNIQUE INDEX ux_exhibitors_tenant_pan ON stall_booking.exhibitors(tenant_id, pan) WHERE is_deleted = false;

CREATE TABLE stall_booking.billing_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES stall_booking.tenants(id),
  exhibitor_id uuid NOT NULL REFERENCES stall_booking.exhibitors(id),
  billing_legal_name varchar(150) NOT NULL,
  billing_address varchar(500) NOT NULL,
  billing_city varchar(100) NOT NULL,
  billing_state varchar(100) NOT NULL,
  billing_state_code char(2) NOT NULL,
  billing_pincode varchar(12) NOT NULL,
  billing_country varchar(100) NOT NULL DEFAULT 'India',
  billing_gstin varchar(15) NOT NULL,
  billing_pan varchar(10) NOT NULL,
  place_of_supply varchar(100) NOT NULL,
  billing_contact_person varchar(100) NOT NULL,
  billing_email varchar(150) NOT NULL,
  billing_mobile varchar(30) NOT NULL,
  is_default boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  deleted_by uuid,
  is_deleted boolean NOT NULL DEFAULT false,
  correlation_id varchar(100),
  CONSTRAINT ck_billing_gstin CHECK (billing_gstin ~ '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$'),
  CONSTRAINT ck_billing_pan CHECK (billing_pan ~ '^[A-Z]{5}[0-9]{4}[A-Z]$')
);

CREATE UNIQUE INDEX ux_billing_default ON stall_booking.billing_profiles(exhibitor_id) WHERE is_default = true AND is_deleted = false;

CREATE TABLE stall_booking.stall_bookings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES stall_booking.tenants(id),
  event_id uuid NOT NULL REFERENCES stall_booking.events(id),
  exhibitor_id uuid NOT NULL REFERENCES stall_booking.exhibitors(id),
  billing_profile_id uuid NOT NULL REFERENCES stall_booking.billing_profiles(id),
  requested_stall_size_id uuid NOT NULL REFERENCES stall_booking.stall_sizes(id),
  allocated_stall_id uuid REFERENCES stall_booking.stalls(id),
  booking_registration_number varchar(40) NOT NULL UNIQUE,
  booking_date timestamptz NOT NULL DEFAULT now(),
  booking_status varchar(50) NOT NULL,
  fascia_name varchar(25) NOT NULL,
  display_notes varchar(500),
  electrical_requirement varchar(500),
  special_requirement varchar(500),
  hazardous_demo_declared boolean NOT NULL DEFAULT false,
  terms_accepted boolean NOT NULL,
  accuracy_accepted boolean NOT NULL,
  payment_timeline_accepted boolean NOT NULL,
  cancellation_policy_accepted boolean NOT NULL,
  privacy_consent_accepted boolean NOT NULL,
  declarant_name varchar(100) NOT NULL,
  declarant_designation varchar(100) NOT NULL,
  declaration_date date NOT NULL,
  block_expires_at timestamptz,
  last_email_sent_at timestamptz,
  confirmed_at timestamptz,
  cancelled_at timestamptz,
  cancellation_reason varchar(500),
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  deleted_by uuid,
  is_deleted boolean NOT NULL DEFAULT false,
  correlation_id varchar(100),
  CONSTRAINT ck_booking_status CHECK (booking_status IN ('Draft','Submitted','UnderReview','BlockedAwaitingPayment','PaymentSubmitted','PaymentVerified','PaymentRejected','Confirmed','ReleasedDueToNonPayment','Cancelled','Closed')),
  CONSTRAINT ck_booking_terms CHECK (terms_accepted AND accuracy_accepted AND payment_timeline_accepted AND cancellation_policy_accepted AND privacy_consent_accepted),
  CONSTRAINT ck_booking_block_expiry CHECK (booking_status <> 'BlockedAwaitingPayment' OR block_expires_at IS NOT NULL),
  CONSTRAINT ck_booking_confirmed_requires_stall CHECK (booking_status <> 'Confirmed' OR allocated_stall_id IS NOT NULL)
);

ALTER TABLE stall_booking.stalls
  ADD CONSTRAINT fk_stalls_current_booking FOREIGN KEY (current_booking_id) REFERENCES stall_booking.stall_bookings(id);

CREATE TABLE stall_booking.stall_allocations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES stall_booking.tenants(id),
  event_id uuid NOT NULL REFERENCES stall_booking.events(id),
  booking_id uuid NOT NULL REFERENCES stall_booking.stall_bookings(id),
  stall_id uuid NOT NULL REFERENCES stall_booking.stalls(id),
  allocation_status varchar(40) NOT NULL,
  blocked_at timestamptz NOT NULL,
  blocked_by uuid NOT NULL,
  block_expires_at timestamptz NOT NULL,
  frozen_at timestamptz,
  frozen_by uuid,
  released_at timestamptz,
  released_by uuid,
  release_reason varchar(500),
  previous_stall_id uuid REFERENCES stall_booking.stalls(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  deleted_by uuid,
  is_deleted boolean NOT NULL DEFAULT false,
  correlation_id varchar(100),
  CONSTRAINT ck_allocation_status CHECK (allocation_status IN ('Blocked','Frozen','Released','Cancelled','Changed')),
  CONSTRAINT ck_allocation_frozen CHECK (allocation_status <> 'Frozen' OR frozen_at IS NOT NULL),
  CONSTRAINT ck_allocation_release CHECK (allocation_status NOT IN ('Released','Cancelled') OR release_reason IS NOT NULL)
);

CREATE UNIQUE INDEX ux_active_allocation_per_booking ON stall_booking.stall_allocations(booking_id) WHERE allocation_status IN ('Blocked','Frozen') AND is_deleted = false;
CREATE UNIQUE INDEX ux_active_allocation_per_stall ON stall_booking.stall_allocations(stall_id) WHERE allocation_status IN ('Blocked','Frozen') AND is_deleted = false;

CREATE TABLE stall_booking.file_attachments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES stall_booking.tenants(id),
  event_id uuid REFERENCES stall_booking.events(id),
  booking_id uuid REFERENCES stall_booking.stall_bookings(id),
  file_category varchar(40) NOT NULL,
  original_file_name varchar(255) NOT NULL,
  stored_file_name varchar(255) NOT NULL,
  content_type varchar(100) NOT NULL,
  file_size_bytes bigint NOT NULL,
  checksum_sha256 char(64) NOT NULL,
  storage_path varchar(500) NOT NULL,
  uploaded_by uuid,
  uploaded_at timestamptz NOT NULL DEFAULT now(),
  scan_status varchar(40) NOT NULL DEFAULT 'Pending',
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  deleted_by uuid,
  is_deleted boolean NOT NULL DEFAULT false,
  correlation_id varchar(100),
  CONSTRAINT ck_file_size CHECK (file_size_bytes > 0),
  CONSTRAINT ck_file_category CHECK (file_category IN ('GSTCertificate','UdyamCertificate','PAN','PaymentProof','ProformaInvoicePdf','Other')),
  CONSTRAINT ck_file_scan_status CHECK (scan_status IN ('Pending','Clean','Suspicious','Failed','NotRequired'))
);

CREATE TABLE stall_booking.payments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES stall_booking.tenants(id),
  event_id uuid NOT NULL REFERENCES stall_booking.events(id),
  booking_id uuid NOT NULL REFERENCES stall_booking.stall_bookings(id),
  payment_reference_number varchar(100) NOT NULL,
  payment_mode varchar(40) NOT NULL,
  payer_name varchar(150) NOT NULL,
  payer_bank varchar(150),
  amount_paid numeric(14,2) NOT NULL,
  payment_date date NOT NULL,
  payment_received_date timestamptz,
  bank_account_matched boolean NOT NULL DEFAULT false,
  payment_proof_file_id uuid REFERENCES stall_booking.file_attachments(id),
  verification_status varchar(50) NOT NULL DEFAULT 'Submitted',
  verified_by uuid,
  verified_at timestamptz,
  rejection_reason varchar(500),
  remarks varchar(500),
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  deleted_by uuid,
  is_deleted boolean NOT NULL DEFAULT false,
  correlation_id varchar(100),
  CONSTRAINT ck_payment_amount CHECK (amount_paid > 0),
  CONSTRAINT ck_payment_status CHECK (verification_status IN ('Pending','Submitted','Verified','Rejected','ClarificationRequired')),
  CONSTRAINT ck_payment_verified CHECK (verification_status <> 'Verified' OR (verified_by IS NOT NULL AND verified_at IS NOT NULL)),
  CONSTRAINT ck_payment_rejected CHECK (verification_status <> 'Rejected' OR rejection_reason IS NOT NULL)
);

CREATE UNIQUE INDEX ux_payment_reference ON stall_booking.payments(event_id, payment_reference_number) WHERE is_deleted = false;

CREATE TABLE stall_booking.proforma_invoices (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES stall_booking.tenants(id),
  event_id uuid NOT NULL REFERENCES stall_booking.events(id),
  booking_id uuid NOT NULL REFERENCES stall_booking.stall_bookings(id),
  invoice_number varchar(50) NOT NULL UNIQUE,
  invoice_date date NOT NULL,
  invoice_status varchar(50) NOT NULL,
  seller_legal_name varchar(180) NOT NULL,
  seller_address varchar(500) NOT NULL,
  seller_gstin varchar(15) NOT NULL,
  seller_pan varchar(10) NOT NULL,
  buyer_legal_name varchar(180) NOT NULL,
  buyer_address varchar(500) NOT NULL,
  buyer_gstin varchar(15) NOT NULL,
  buyer_pan varchar(10) NOT NULL,
  place_of_supply varchar(100) NOT NULL,
  stall_number varchar(40) NOT NULL,
  stall_size_display varchar(80) NOT NULL,
  hsn_sac varchar(20) NOT NULL DEFAULT '998397',
  description varchar(500) NOT NULL,
  base_amount numeric(14,2) NOT NULL,
  gst_percentage numeric(5,2) NOT NULL,
  gst_amount numeric(14,2) NOT NULL,
  total_amount numeric(14,2) NOT NULL,
  amount_in_words varchar(500) NOT NULL,
  tax_amount_in_words varchar(500) NOT NULL,
  notes varchar(500),
  bank_account_name varchar(150) NOT NULL,
  bank_name varchar(150) NOT NULL,
  bank_account_number varchar(60) NOT NULL,
  ifsc_code varchar(20) NOT NULL,
  branch_name varchar(150) NOT NULL,
  pdf_file_id uuid REFERENCES stall_booking.file_attachments(id),
  generated_by uuid NOT NULL,
  generated_at timestamptz NOT NULL,
  sent_by uuid,
  sent_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  deleted_by uuid,
  is_deleted boolean NOT NULL DEFAULT false,
  correlation_id varchar(100),
  CONSTRAINT ck_invoice_status CHECK (invoice_status IN ('Draft','Generated','Sent','Cancelled','Revised')),
  CONSTRAINT ck_invoice_total CHECK (total_amount = round(base_amount + gst_amount, 2))
);

CREATE UNIQUE INDEX ux_active_invoice_per_booking ON stall_booking.proforma_invoices(booking_id) WHERE invoice_status <> 'Cancelled' AND is_deleted = false;

CREATE TABLE stall_booking.email_templates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES stall_booking.tenants(id),
  event_id uuid REFERENCES stall_booking.events(id),
  template_code varchar(80) NOT NULL,
  subject_template varchar(300) NOT NULL,
  body_html_template text NOT NULL,
  body_text_template text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  deleted_by uuid,
  is_deleted boolean NOT NULL DEFAULT false,
  correlation_id varchar(100),
  UNIQUE (tenant_id, event_id, template_code)
);

CREATE TABLE stall_booking.email_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES stall_booking.tenants(id),
  event_id uuid REFERENCES stall_booking.events(id),
  booking_id uuid REFERENCES stall_booking.stall_bookings(id),
  to_email varchar(150) NOT NULL,
  cc_email varchar(500),
  bcc_email varchar(500),
  subject varchar(300) NOT NULL,
  body_snapshot text NOT NULL,
  template_code varchar(80) NOT NULL,
  status varchar(40) NOT NULL,
  provider_message_id varchar(200),
  failure_reason varchar(1000),
  sent_at timestamptz,
  retry_count int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  deleted_by uuid,
  is_deleted boolean NOT NULL DEFAULT false,
  correlation_id varchar(100),
  CONSTRAINT ck_email_status CHECK (status IN ('Pending','Sent','Failed','Retrying'))
);

CREATE TABLE stall_booking.users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES stall_booking.tenants(id),
  event_id uuid REFERENCES stall_booking.events(id),
  full_name varchar(150) NOT NULL,
  email varchar(150) NOT NULL,
  mobile varchar(30),
  password_hash varchar(500) NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  last_login_at timestamptz,
  failed_login_count int NOT NULL DEFAULT 0,
  locked_until timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  deleted_by uuid,
  is_deleted boolean NOT NULL DEFAULT false,
  correlation_id varchar(100),
  UNIQUE (tenant_id, email)
);

CREATE TABLE stall_booking.roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES stall_booking.tenants(id),
  event_id uuid REFERENCES stall_booking.events(id),
  role_code varchar(80) NOT NULL,
  role_name varchar(120) NOT NULL,
  description varchar(500),
  is_system_role boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  deleted_by uuid,
  is_deleted boolean NOT NULL DEFAULT false,
  correlation_id varchar(100),
  UNIQUE (tenant_id, role_code)
);

CREATE TABLE stall_booking.permissions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES stall_booking.tenants(id),
  event_id uuid REFERENCES stall_booking.events(id),
  permission_code varchar(120) NOT NULL UNIQUE,
  permission_name varchar(150) NOT NULL,
  module_name varchar(100) NOT NULL,
  action_name varchar(100) NOT NULL,
  description varchar(500),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  deleted_by uuid,
  is_deleted boolean NOT NULL DEFAULT false,
  correlation_id varchar(100)
);

CREATE TABLE stall_booking.user_roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES stall_booking.tenants(id),
  event_id uuid REFERENCES stall_booking.events(id),
  user_id uuid NOT NULL REFERENCES stall_booking.users(id),
  role_id uuid NOT NULL REFERENCES stall_booking.roles(id),
  valid_from date NOT NULL DEFAULT current_date,
  valid_to date,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  deleted_by uuid,
  is_deleted boolean NOT NULL DEFAULT false,
  correlation_id varchar(100),
  UNIQUE (tenant_id, event_id, user_id, role_id)
);

CREATE TABLE stall_booking.role_permissions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES stall_booking.tenants(id),
  event_id uuid REFERENCES stall_booking.events(id),
  role_id uuid NOT NULL REFERENCES stall_booking.roles(id),
  permission_id uuid NOT NULL REFERENCES stall_booking.permissions(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  deleted_by uuid,
  is_deleted boolean NOT NULL DEFAULT false,
  correlation_id varchar(100),
  UNIQUE (role_id, permission_id)
);

CREATE TABLE stall_booking.audit_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES stall_booking.tenants(id),
  event_id uuid REFERENCES stall_booking.events(id),
  actor_user_id uuid REFERENCES stall_booking.users(id),
  entity_name varchar(120) NOT NULL,
  entity_id uuid NOT NULL,
  action varchar(120) NOT NULL,
  old_values jsonb,
  new_values jsonb,
  ip_address varchar(80),
  user_agent varchar(500),
  correlation_id varchar(100),
  occurred_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE stall_booking.number_sequences (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES stall_booking.tenants(id),
  event_id uuid REFERENCES stall_booking.events(id),
  sequence_code varchar(80) NOT NULL,
  sequence_date date,
  prefix varchar(40) NOT NULL,
  current_number bigint NOT NULL DEFAULT 0,
  padding_length int NOT NULL DEFAULT 4,
  reset_frequency varchar(20) NOT NULL DEFAULT 'Daily',
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  deleted_by uuid,
  is_deleted boolean NOT NULL DEFAULT false,
  correlation_id varchar(100),
  UNIQUE (tenant_id, event_id, sequence_code, sequence_date),
  CONSTRAINT ck_sequence_reset CHECK (reset_frequency IN ('Never','Daily','Monthly','Yearly'))
);

CREATE TABLE stall_booking.dashboard_snapshots (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES stall_booking.tenants(id),
  event_id uuid NOT NULL REFERENCES stall_booking.events(id),
  snapshot_date date NOT NULL,
  total_stalls int NOT NULL DEFAULT 0,
  available_stalls int NOT NULL DEFAULT 0,
  blocked_stalls int NOT NULL DEFAULT 0,
  frozen_stalls int NOT NULL DEFAULT 0,
  released_stalls int NOT NULL DEFAULT 0,
  payment_pending_count int NOT NULL DEFAULT 0,
  payment_received_count int NOT NULL DEFAULT 0,
  payment_verified_count int NOT NULL DEFAULT 0,
  payment_rejected_count int NOT NULL DEFAULT 0,
  invoice_generated_count int NOT NULL DEFAULT 0,
  invoice_sent_count int NOT NULL DEFAULT 0,
  invoice_pending_count int NOT NULL DEFAULT 0,
  snapshot_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (event_id, snapshot_date)
);

CREATE INDEX ix_bookings_event_status ON stall_booking.stall_bookings(event_id, booking_status);
CREATE INDEX ix_bookings_block_expiry ON stall_booking.stall_bookings(block_expires_at);
CREATE INDEX ix_stalls_event_status ON stall_booking.stalls(event_id, current_status);
CREATE INDEX ix_allocations_expiry ON stall_booking.stall_allocations(event_id, allocation_status, block_expires_at);
CREATE INDEX ix_payments_status ON stall_booking.payments(event_id, verification_status);
CREATE INDEX ix_invoices_status ON stall_booking.proforma_invoices(event_id, invoice_status);
CREATE INDEX ix_email_logs_status ON stall_booking.email_logs(status, created_at);
CREATE INDEX ix_audit_entity ON stall_booking.audit_logs(entity_name, entity_id, occurred_at);
