import { Link } from 'react-router'; import { Plus } from 'lucide-react'; 
import { Button } from '../../../../components/ui/Button';
import { Card } from '../../../../components/ui/Card';
import { LoadingState, ErrorState } from '../../../../components/ui/PageStates';
import { useMeetings } from '../../../../services/buyer/hooks';
// import { StatusBadge } from '../../../../shared/StatusBadge';
import { ScreenShell } from '../shared/ScreenShell';
import { StatusBadge } from '../../../../components/ui/StatusBadge';
import { RefreshListButton } from '../../../../shared/components/RefreshListButton';

const hours=['09:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00'];
export default function MeetingsPage(){const q=useMeetings();if(q.isLoading)return <LoadingState/>;if(q.isError)return <ErrorState error={q.error}/>;return <ScreenShell screen={15} title="Buyer Meetings — Calendar" subtitle="Plan, manage and complete Buyer-Seller appointments." actions={<div className="flex items-center gap-2"><RefreshListButton onRefresh={() => q.refetch()} /><Link to="/buyer/meetings/new"><Button><Plus className="h-4 w-4"/>Schedule Meeting</Button></Link></div>}><div className="grid gap-4 xl:grid-cols-[1fr_18rem]"><Card className="p-4"><div className="mb-4 flex justify-between"><div><b className="text-sm">18–19 September 2026</b><p className="text-[10px] text-slate-400">Event timezone: Asia/Kolkata</p></div><div className="flex gap-2 text-xs"><button className="rounded-lg bg-brand-50 px-3 py-1 font-bold text-brand-700">Day</button><button className="rounded-lg px-3 py-1">List View</button></div></div><div className="grid grid-cols-[4rem_1fr_1fr] border border-slate-200 text-xs"><div className="bg-slate-50 p-2"></div><div className="border-l border-slate-200 bg-slate-50 p-2 font-bold">Fri 18 Sep</div><div className="border-l border-slate-200 bg-slate-50 p-2 font-bold">Sat 19 Sep</div>{hours.flatMap((h,i)=>[<div key={`${h}t`} className="border-t border-slate-100 p-2 text-slate-400">{h}</div>,<div key={`${h}a`} className="min-h-14 border-l border-t border-slate-100 p-1">{q.data?.filter(m=>m.startTime.startsWith(h.slice(0,2))).map(m=><Link key={m.id} to={`/buyer/meetings/${m.id}`} className="block rounded-lg bg-emerald-50 p-2 text-[10px] text-emerald-800"><b>{m.startTime} {m.supplierName}</b><br/>{m.requirementCode}</Link>)}</div>,<div key={`${h}b`} className="min-h-14 border-l border-t border-slate-100 p-1"></div>])}</div></Card><Card className="p-4"><h2 className="text-sm font-extrabold">Today's Summary</h2><div className="mt-4 space-y-3">{[['Meetings',q.data?.length??0],['Confirmed',q.data?.filter(x=>['CONFIRMED','CHECKED_IN','IN_PROGRESS'].includes(x.status.toUpperCase())).length??0],['Pending',q.data?.filter(x=>x.status.toUpperCase()==='REQUESTED').length??0],['No-show',q.data?.filter(x=>x.status.toUpperCase()==='NO_SHOW').length??0]].map(([l,v])=><div className="flex justify-between rounded-lg bg-slate-50 p-3 text-xs" key={String(l)}><span>{l}</span><b>{v}</b></div>)}</div><div className="mt-5 space-y-2">{q.data?.map(m=><div className="rounded-lg border border-slate-100 p-2" key={m.id}><b className="text-[11px]">{m.startTime} · {m.supplierName}</b><div className="mt-1"><StatusBadge status={m.status}/></div></div>)}</div></Card></div></ScreenShell>;}
