<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="../MSME.StallBooking.Application/MSME.StallBooking.Application.csproj" />
		<ProjectReference Include="../MSME.StallBooking.Domain/MSME.StallBooking.Domain.csproj" />
		<ProjectReference Include="../MSME.StallBooking.Persistence/MSME.StallBooking.Persistence.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="MailKit" Version="4.17.0" />
		<PackageReference Include="MimeKit" Version="4.17.0" />
		<PackageReference Include="QuestPDF" Version="2026.6.0" />
		<PackageReference Include="QRCoder" Version="1.6.0" />
	</ItemGroup>
</Project>